services:
  app-dev:
    build:
      context: .
      target: dev
    image: blogmura-node:dev
    working_dir: /app
    volumes:
      - ./:/app
      # keep container's node_modules instead of host's
      - /app/node_modules
    env_file:
      - .env
    environment:
      - HEADLESS=true
      - TZ=Asia/Tokyo
    shm_size: "1g"
    # If you run Docker Desktop (Linux containers), this is fine on Windows too
    # For WSL2/X11 GUI forwarding, set HEADLESS=false and configure DISPLAY
    command: npm run dev

  app:
    build:
      context: .
      target: runner
    image: blogmura-node:latest
    env_file:
      - .env
    environment:
      - HEADLESS=true
      - TZ=Asia/Tokyo
    shm_size: "1g"
    # run once and exit
    command: node dist/index.js
